const readFileSync = require('fs').readFileSync;
const readdirSync = require('fs').readdirSync;
const unlinkSync = require('fs').unlinkSync;

readdirSync(__dirname + '/packages/' + process.argv[2]).forEach(entry => {
  try {
    if (
      /\@autogenerated\b/.test(
        readFileSync(
          __dirname + '/packages/' + process.argv[2] + '/' + entry,
          'utf8',
        ),
      )
    ) {
      unlinkSync(__dirname + '/packages/' + process.argv[2] + '/' + entry);
    }
  } catch (ex) {
    if (ex.code !== 'EISDIR') {
      throw ex;
    }
  }
});
