version: 2

refs:
  - &container
    docker:
      - image: node:12
    working_directory: ~/repo
  - &restore_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-
  - &save_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "yarn.lock" }}
  - &npm_auth
    run:
      name: NPM Auth
      command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - &bolt_install
    run:
      name: Bolt Install
      command: yarn global add bolt && bolt
  - &build
    run:
      name: Build
      command: bolt run build:all
  - &test
    run:
      name: Test
      command: bolt run test

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *restore_cache
      - *npm_auth
      - *bolt_install
      - *save_cache
      - *build
      - *test

  publish-dry-run:
    <<: *container
    steps:
      - checkout
      - *restore_cache
      - *npm_auth
      - *bolt_install
      - *save_cache
      - *build
      - *test
      - run:
          name: Release (Dry Run)
          command: npx rollingversions publish --dry-run

  publish:
    <<: *container
    steps:
      - checkout
      - *restore_cache
      - *npm_auth
      - *bolt_install
      - *save_cache
      - *build
      - *test
      - run:
          name: Release
          command: npx rollingversions publish

workflows:
  version: 2
  all:
    jobs:
      - all:
          filters:
            branches:
              ignore:
                - master
  master:
    jobs:
      - publish-dry-run: 
        filters: 
          branches: 
            only: master

    - publish-approval: 
        type: approval
        requires: 
          - publish-dry-run

    - publish: 
        requires: 
          - publish-approval
        filters: 
          branches: 
            only: master
