import BaseError from '@authentication/base-error';

/**
 * `InternalOAuthError` error.
 *
 * InternalOAuthError wraps errors generated by @moped/oauth.  By wrapping these
 * objects, error messages can be formatted in a manner that aids in debugging
 * OAuth issues.
 */
export default class InternalOAuthError extends BaseError {
  readonly oauthMessage: string;
  readonly oauthError: Error;
  constructor(message: string, oauthError?: any) {
    let m = message;
    if (oauthError) {
      if (oauthError instanceof Error) {
        m = oauthError.toString();
      } else if (oauthError.statusCode && oauthError.data) {
        m +=
          ' (status: ' +
          oauthError.statusCode +
          ' data: ' +
          oauthError.data +
          ')';
      }
    }
    super('INTERNAL_OAUTH_ERROR', m);
    this.oauthMessage = message;
    this.oauthError = oauthError;
  }
}
